apiVersion: v1
kind: Service
metadata:
  labels:
    service: final-frontend-service
  name: final-frontend-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: final-frontend