name: Docker Compose Actions Workflow
on:
  push:
    branches:
    - main
jobs:
  getEnv:
    name: Map AWS secret to Github ENV
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Build the stack
      run: |
          docker login -u ${{ vars.DOCKER_NAME }} -p ${{ secrets.DOCKER_PASS }}
          cd ./client
          echo '-----------------------------------------------'
          echo '-----------------------------------------------'
          docker build -t ${{ vars.DOCKER_NAME }}/final-frontend:latest .
          echo '-----------------------------------------------'
          echo '-----------------------------------------------'
          docker push ${{ vars.DOCKER_NAME }}/final-frontend:latest
