name: Docker Compose Actions Workflow
on:
  push:
    branches:
    - main
jobs:
  getEnv:
    name: Map AWS secret to Github ENV
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Read secrets from AWS Secrets Manager into environment variables
      uses: abhilash1in/aws-secrets-manager-action@v2.1.0
      with:
        secrets: dev/frontend/env
        parse-json: true
    - name: print env
      run: |
          if [ -z ${DEV_FRONTEND_ENV_API_ID+x} ]; then echo "DEV_FRONTEND_ENV_API_ID is unset"; else echo "DEV_FRONTEND_ENV_API_ID is set to '$DEV_FRONTEND_ENV_API_ID'"; fi
        
