name: Docker Compose Actions Workflow
on:
  push:
    branches:
    - main
jobs:
  getEnv:
    name: Map AWS secret to Github ENV
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Read secrets from AWS Secrets Manager into environment variables
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          dev/frontend/env
        parse-json-secrets: true

    - name: print env
      run: |
        echo $DEV_FRONTEND_ENV_API_ID
        echo "$DEV_FRONTEND_ENV_API_ID"
        echo ${{ secret.DEV_FRONTEND_ENV_API_ID }}
        
